export const actions = {
  GET_TOPIC_PHOTOS: 'GET_TOPIC_PHOTOS',
  GET_TOPIC_PHOTOS_SUCCESS: 'GET_TOPIC_PHOTOS_SUCCESS',
  GET_EDITORIAL_FEED_PHOTOS: 'GET_EDITORIAL_FEED_PHOTOS',
  GET_EDITORIAL_FEED_PHOTOS_SUCCESS: 'GET_EDITORIAL_FEED_PHOTOS_SUCCESS',
  GET_PHOTO_BY_ID: 'GET_PHOTO_BY_ID',
  GET_PHOTO_BY_ID_SUCCESS: 'GET_PHOTO_BY_ID_SUCCESS'
}
